---
server_ips:
 - 192.168.100.101
 - 192.168.100.102
 - 192.168.100.103

consul_interface: eth1

consul_cfg_dir: /var/lib/consul/config.d

consul_data_dir: /var/lib/consul/data

consul_log_level: INFO

consul_key: ZrWamm/G+TtnigcxX1EZiw==
