---
- name: Install consul
  dnf: name=consul state=present

- name: Install vault
  unarchive: copy=no src=https://releases.hashicorp.com/vault/0.5.2/vault_0.5.2_linux_amd64.zip dest=/usr/local/bin mode=0755 owner=root group=root
 
- name: Add consul group
  group: name=consul

- name: Add consul user
  user: name=consul comment="consul user" group=consul createhome=yes shell=/sbin/nologin home={{ consul_dir }}

- name: Add vault group
  group: name=vault

- name: Add vault user
  user: name=vault comment="vault user" group=vault createhome=yes shell=/sbin/nologin home={{ vault_dir }}

- name: Create consul config dir
  file: path={{ consul_cfg_dir }} mode=775 state=directory owner=consul group=consul

- name: Create consul data dir
  file: path={{ consul_data_dir }}/data mode=775 state=directory owner=consul group=consul

- name: Add consul systemd service
  template: src=consul.service.j2 dest=/etc/systemd/system/consul.service owner=root group=root mode=0644

- name: Copy consul config file
  template: src=cluster.json.j2 dest={{ consul_cfg_dir }}/cluster.json owner=consul group=consul
  notify: Reload consul

- name: Add vault systemd service
  template: src=vault.service.j2 dest=/etc/systemd/system/vault.service owner=root group=root mode=0644

- name: Copy vault config file
  template: src=vault.conf.j2 dest={{ vault_dir }}/vault.conf owner=vault group=vault
  notify: Reload vault
