---
- name: Prepare FC23 cloud box for ansible
  raw: dnf -y install python-simplejson python2-dnf libselinux-python libsemanage-python unzip
- name: gather facts
  setup:

- name: Install consul
  dnf: name=consul state=present

- name: Install vault
  unarchive: 
        copy=no
        src=https://releases.hashicorp.com/vault/0.5.2/vault_0.5.2_linux_amd64.zip
        dest=/usr/local/bin
        creates=/usr/local/bin/vault
        mode=0755 owner=root group=root
 
- name: Add consul group
  group: name=consul

- name: Add consul user
  user: name=consul comment="consul user" group=consul createhome=yes shell=/sbin/nologin home={{ consul_dir }}

- name: Add vault group
  group: name=vault

- name: Add vault user
  user: name=vault comment="vault user" group=vault createhome=yes shell=/bin/bash home={{ vault_dir }}

- name: Create consul config dir
  file: path={{ consul_cfg_dir }} mode=775 state=directory owner=consul group=consul

- name: Create consul data dir
  file: path={{ consul_data_dir }}/data mode=775 state=directory owner=consul group=consul

- name: Add consul systemd service
  template: src=consul.service.j2 dest=/etc/systemd/system/consul.service owner=root group=root mode=0644
  notify: Reload consul
