---
- name: Install consul
  dnf: name=consul state=present

- name: Install vault
  unarchive: copy=no src=https://releases.hashicorp.com/vault/0.5.2/vault_0.5.2_linux_amd64.zip dest=/usr/local/bin mode=0755 owner=root group=root
 
- name: Add consul group
  group: name=consul

- name: Add consul user
  user: name=consul comment="consul user" group=consul createhome=yes shell=/sbin/nologin home={{ consul_dir }}

- name: Add vault group
  group: name=vault

- name: Add vault user
  user: name=vault comment="vault user" group=vault createhome=yes shell=/bin/bash home={{ vault_dir }}

- name: Create consul config dir
  file: path={{ consul_cfg_dir }} mode=775 state=directory owner=consul group=consul

- name: Create consul data dir
  file: path={{ consul_data_dir }}/data mode=775 state=directory owner=consul group=consul

- name: Add consul systemd service
  template: src=consul.service.j2 dest=/etc/systemd/system/consul.service owner=root group=root mode=0644

- name: Copy consul config file
  template: src=client.json.j2 dest={{ consul_cfg_dir }}/client.json owner=consul group=consul
  notify: Reload consul

- name: Init vault
  shell: /usr/local/bin/vault init -address=http://{{ server_ips.0 }}:8200 -key-shares=1 -key-threshold=1 
  register: vault_init

- name: Deploy vault keys
  template: src=vault.j2 dest=/etc/sysconfig/vault owner=root group=root mode=0600
  delegate_to: "{{item}}"
  with_items: "{{groups['servers']}}"
  when: vault_init.rc == 0
  notify: Restart vault cluster

- name: Deploy root token to vault user
  template: src=vault-token.j2 dest={{ vault_dir }}/.vault-token owner=vault group=vault mode=0600
  delegate_to: "{{item}}"
  with_items: 
        - "{{groups['servers']}}"
        - client
  when: vault_init.rc == 0
